/**
 * EntityOS seed — spreadsheet-driven.
 *
 * Data source: prisma/data/nium-data.json, generated by prisma/data/parse_xlsx.py
 * from the two uploaded spreadsheets (entity-tracker.xlsx and
 * board-meetings-calendar.xlsx). To refresh the data after the sheets change:
 *
 *     python3 prisma/data/parse_xlsx.py \
 *         prisma/data/entity-tracker.xlsx \
 *         prisma/data/board-meetings-calendar.xlsx
 *     npx prisma migrate reset          # wipes DB and re-runs this seed
 *
 * What gets seeded:
 *   - 7 application users (unchanged from previous seed)
 *   - 35 entities from Master Sheet (28 active + 7 dissolved), with parent links
 *   - Directors parsed from the D&Os column
 *   - Licenses parsed from the Licenses column (dates left null — unknown)
 *   - Board meetings parsed from the Subsidiaries Calendar sheet
 *
 * Intentionally NOT seeded (no data in spreadsheets):
 *   - ComplianceObligation
 *   - RegulatoryCapital
 *   - BankAccount
 *   - Alert
 *   - MeetingAttendee (attendee names are free-text and don't map 1:1 to directors)
 *   - MeetingDocument, MeetingResolution
 */
import { prisma } from '../lib/prisma';
import { readFileSync } from 'fs';
import { join } from 'path';

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function toDate(s: string | Date | null | undefined): Date | undefined {
  if (!s) return undefined;
  const d = s instanceof Date ? s : new Date(s);
  return isNaN(d.getTime()) ? undefined : d;
}

// Strip keys whose value is `undefined` so Prisma doesn't interpret them as
// "missing required argument". `null` is kept — it's a valid NULL value for
// nullable columns.
// Strips keys whose value is `undefined` AND converts `null` -> undefined for
// non-nullable columns. Prisma treats explicit `undefined` as "field not set"
// (uses DB default / leaves nullable as NULL), which is what we want for
// optional fields whose types in the stale generated client may still be
// strict. Re-run `prisma generate` after any schema change to tighten this.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function clean<T extends Record<string, any>>(obj: T): T {
  return Object.fromEntries(
    Object.entries(obj)
      .filter(([, v]) => v !== undefined)
      .map(([k, v]) => [k, v === null ? undefined : v])
  ) as T;
}

function slugEmail(name: string): string {
  return (
    name
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/[^a-z0-9\s]/g, '')
      .trim()
      .replace(/\s+/g, '.') + '@nium.com'
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Data file
// ─────────────────────────────────────────────────────────────────────────────

interface DirectorRow {
  name: string;
  role: string;
}
interface LicenseRow {
  licenseType: string;
  licenseNumber: string;
  regulator: string;
}
interface EntityRow {
  id: string;
  name: string;
  country: string;
  legalStructure: string;
  registrationNumber: string;
  registeredAddress: string;
  incorporationDate: string | null;
  financialYearEnd: string;
  governingLaw: string;
  auditor: string | null;
  regulator: string | null;
  isIxarisEntity: boolean;
  status: 'active' | 'dormant' | 'dissolved' | 'in_formation';
  notes: string | null;
  parentEntityId: string | null;
  purpose?: string | null;
  minCapital?: string | null;
  corporateSecretary?: string | null;
  corporateSecretaryContact?: string | null;
  _directors: DirectorRow[];
  _licenses: LicenseRow[];
  _governance?: Record<string, string | null>;
}
interface MeetingRow {
  id: string;
  entityId: string;
  meetingType: string;
  meetingDate: string;
  meetingTime: string;
  timezone: string;
  locationType: 'physical' | 'virtual' | 'hybrid';
  location: string | null;
  virtualLink: string | null;
  agenda: string;
  chair: string;
  quorumRequired: number;
  status: 'draft' | 'scheduled' | 'completed' | 'cancelled';
  minutes: string | null;
  notes: string | null;
  recurrence: string | null;
  heldAt: string | null;
  confirmedBy: string | null;
  directorsPresent: number | null;
  minutesUrl: string | null;
  createdBy: string;
  _attendeesRaw?: string | null;
  _owner?: string | null;
  _circulationDeadline?: string | null;
  _materialsDeadline?: string | null;
  _minutesDeadline?: string | null;
}
interface DataFile {
  generatedAt: string;
  entities: EntityRow[];
  meetings: MeetingRow[];
}

interface CalendarEntry {
  country: string;
  jurisdiction: string;
  entity_name: string;
  regulator: string;
  report_name: string;
  frequency: string;
  deadline_raw: string;
  due_date: string;
  recurrence: string;
  lead_team: string;
  compliance_dri: string;
  finance_dri: string;
}
interface CalendarFile {
  year: number;
  entries: CalendarEntry[];
}

const DATA_PATH = join(__dirname, 'data', 'nium-data.json');
const data: DataFile = JSON.parse(readFileSync(DATA_PATH, 'utf-8'));

const CAL_PATH = join(__dirname, 'data', 'regulatory-calendar-2026.json');
const calData: CalendarFile = JSON.parse(readFileSync(CAL_PATH, 'utf-8'));

// Fuzzy entity name matcher — normalise both sides, try exact then substring
function normName(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9 ]/g, '').replace(/\s+/g, ' ').trim();
}
function matchEntityId(name: string, entities: { id: string; name: string }[]): string | null {
  const n = normName(name);
  const exact = entities.find(e => normName(e.name) === n);
  if (exact) return exact.id;
  const partial = entities.find(e => normName(e.name).includes(n) || n.includes(normName(e.name)));
  return partial?.id ?? null;
}

// ─────────────────────────────────────────────────────────────────────────────
// MAIN
// ─────────────────────────────────────────────────────────────────────────────

async function main() {
  console.log('Starting seed...');
  console.log(`Data file generated: ${data.generatedAt}`);
  console.log(`Source: prisma/data/nium-data.json`);

  try {
    // ──────────────────────────────────────────────────────────────────────
    // USERS
    // ──────────────────────────────────────────────────────────────────────
    console.log('Seeding users...');
    const users = [
      { id: 'usr-super-001',   name: 'Prajit Nanu',                  email: 'prajit@nium.com',              role: 'super_admin' as const, department: 'Executive',  title: 'CEO' },
      { id: 'usr-admin-001',   name: 'Lia Thomazzi Susin',           email: 'lia.susin@nium.com',           role: 'admin' as const,       department: 'Legal',      title: 'General Counsel' },
      { id: 'usr-legal-001',   name: 'Spencer James Douglas Hanlon', email: 'spencer@nium.com',             role: 'legal' as const,       department: 'Legal',      title: 'Legal Manager' },
      { id: 'usr-legal-002',   name: 'Pratik Gandhi',                email: 'pratik@nium.com',              role: 'legal' as const,       department: 'Legal',      title: 'Senior Legal Counsel' },
      { id: 'usr-finance-001', name: 'Michael Bermingham',           email: 'michael.bermingham@nium.com',  role: 'finance' as const,     department: 'Finance',    title: 'Finance Manager' },
      { id: 'usr-finance-002', name: 'Vinoth Manoharan',             email: 'vinoth@nium.com',              role: 'finance' as const,     department: 'Finance',    title: 'Regulatory Capital Analyst' },
      { id: 'usr-viewer-001',  name: 'Anupam Pahuja',                email: 'anupam@nium.com',              role: 'viewer' as const,      department: 'Operations', title: 'Operations Officer' },
    ];
    for (const u of users) {
      await prisma.user.upsert({
        where: { email: u.email },
        // On re-seed: only sync name and oktaId — never overwrite role, department,
        // title, or isActive (those are managed by admins via the UI)
        update: clean({ name: u.name }),
        create: clean({ ...u, isActive: true }),
      });
    }
    console.log(`✓ Seeded ${users.length} users`);

    // ──────────────────────────────────────────────────────────────────────
    // ENTITIES  (two-pass to satisfy self-referential parentEntityId FK)
    // ──────────────────────────────────────────────────────────────────────
    console.log('Seeding entities...');
    for (const e of data.entities) {
      const notesParts: string[] = [];
      if (e.notes) notesParts.push(e.notes);
      if (e.purpose) notesParts.push(`Purpose: ${e.purpose}`);
      if (e.minCapital) notesParts.push(`Min. capital: ${e.minCapital}`);
      if (e.corporateSecretary) notesParts.push(`Corp sec: ${e.corporateSecretary}`);
      if (e.corporateSecretaryContact) notesParts.push(`Contact: ${e.corporateSecretaryContact}`);

      const data1 = clean({
        id: e.id,
        name: e.name,
        country: e.country,
        legalStructure: e.legalStructure,
        registrationNumber: e.registrationNumber || 'N/A',
        registeredAddress: e.registeredAddress || e.country,
        incorporationDate: toDate(e.incorporationDate) ?? new Date('2015-01-01'),
        financialYearEnd: e.financialYearEnd || '31 December',
        governingLaw: e.governingLaw || e.country,
        auditor: e.auditor,
        regulator: e.regulator,
        isIxarisEntity: e.isIxarisEntity,
        status: e.status,
        notes: notesParts.length ? notesParts.join('\n\n') : null,
        parentEntityId: null, // pass 2 sets this
      });
      // On re-seed: never overwrite user-edited entity fields (name, financialYearEnd,
      // status, notes, registeredAddress, auditor, regulator, etc.)
      // Only create if this entity doesn't exist yet.
      const existingEntity = await prisma.entity.findUnique({ where: { id: e.id } });
      if (!existingEntity) {
        await prisma.entity.create({ data: data1 });
      }
    }
    // Pass 2: parent linkage (safe to always set — it's a FK, not a user-edited field)
    for (const e of data.entities) {
      if (e.parentEntityId) {
        await prisma.entity.update({
          where: { id: e.id },
          data: { parentEntityId: e.parentEntityId },
        });
      }
    }
    console.log(`✓ Seeded ${data.entities.length} entities (${data.entities.filter(e => e.status === 'active').length} active, ${data.entities.filter(e => e.status === 'dissolved').length} dissolved)`);

    // ──────────────────────────────────────────────────────────────────────
    // DIRECTORS
    // ──────────────────────────────────────────────────────────────────────
    console.log('Seeding directors (create-only — preserves user edits)...');
    // NEVER deleteMany — that would wipe user-edited appointment dates, emails, etc.
    // Instead: create new directors that don't exist yet; skip existing ones entirely.
    let dirCreated = 0; let dirSkipped = 0;
    for (const e of data.entities) {
      let idx = 0;
      for (const d of e._directors) {
        idx += 1;
        const id = `dir-${e.id.replace(/^ent-/, '')}-${idx.toString().padStart(2, '0')}`;
        const existingDir = await prisma.director.findUnique({ where: { id } });
        if (existingDir) {
          dirSkipped++;
          continue; // preserve all user edits (email, appointmentDate, termExpiry, etc.)
        }
        await prisma.director.create({
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          data: clean({
            id,
            entityId: e.id,
            name: d.name,
            email: slugEmail(d.name),
            role: d.role || 'Director',
            appointmentDate: toDate(e.incorporationDate) ?? new Date('2020-01-01'),
            isActive: e.status === 'active',
          }) as any,
        });
        dirCreated++;
      }
    }
    console.log(`✓ Directors: ${dirCreated} created, ${dirSkipped} preserved (user edits kept)`);

    // ──────────────────────────────────────────────────────────────────────
    // LICENSES
    // ──────────────────────────────────────────────────────────────────────
    console.log('Seeding licenses (create-only — preserves user edits)...');
    // NEVER deleteMany — that would wipe user-edited expiry dates, statuses, notes, etc.
    let licCreated = 0; let licSkipped = 0;
    for (const e of data.entities) {
      let idx = 0;
      for (const l of e._licenses) {
        idx += 1;
        const id = `lic-${e.id.replace(/^ent-/, '')}-${idx.toString().padStart(2, '0')}`;
        const existingLic = await prisma.license.findUnique({ where: { id } });
        if (existingLic) { licSkipped++; continue; }
        await prisma.license.create({
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          data: clean({
            id,
            entityId: e.id,
            licenseType: l.licenseType,
            regulator: l.regulator || e.regulator || 'N/A',
            licenseNumber: l.licenseNumber || 'N/A',
            issueDate: toDate(e.incorporationDate) ?? new Date('2020-01-01'),
            expiryDate: new Date('2030-12-31'),
            renewalRequired: true,
            renewalLeadDays: 90,
            status: 'active' as const,
          }) as any,
        });
        licCreated++;
      }
    }
    console.log(`✓ Licenses: ${licCreated} created, ${licSkipped} preserved (user edits kept)`);

    // ──────────────────────────────────────────────────────────────────────
    // BOARD MEETINGS
    // ──────────────────────────────────────────────────────────────────────
    console.log('Seeding board meetings (upsert — preserves user edits)...');
    let bmCreated = 0; let bmUpdated = 0;
    for (const m of data.meetings) {
      // Enrich notes with calendar metadata
      const notesParts: string[] = [];
      if (m.notes) notesParts.push(`Status: ${m.notes}`);
      if (m._owner) notesParts.push(`Owner: ${m._owner}`);
      if (m._circulationDeadline) notesParts.push(`Agenda circulation deadline: ${m._circulationDeadline}`);
      if (m._materialsDeadline) notesParts.push(`Materials circulation deadline: ${m._materialsDeadline}`);
      if (m._minutesDeadline) notesParts.push(`Minutes circulation deadline: ${m._minutesDeadline}`);
      if (m._attendeesRaw) notesParts.push(`Attendees (raw):\n${m._attendeesRaw}`);

      // Scheduling fields — synced from source data on update.
      // meetingType and chair are intentionally excluded: users edit these in the UI
      // and they must be preserved across re-seeds.
      const scheduleData = clean({
        entityId: m.entityId,
        meetingDate: toDate(m.meetingDate) ?? new Date('2025-12-31'),
        meetingTime: m.meetingTime || 'TBD',
        timezone: m.timezone || 'UTC',
        locationType: m.locationType,
        location: m.location,
        virtualLink: m.virtualLink,
        agenda: m.agenda || 'Standard board agenda',
        quorumRequired: m.quorumRequired ?? 2,
        recurrence: m.recurrence,
      });

      const existing = await prisma.boardMeeting.findUnique({ where: { id: m.id } });

      if (existing) {
        // Update only scheduling fields — preserve user-entered operational data
        // (status, notes, heldAt, confirmedBy, directorsPresent, minutesUrl)
        await (prisma.boardMeeting as any).update({ where: { id: m.id }, data: scheduleData });
        bmUpdated++;
      } else {
        // First-time creation — include all fields
        await (prisma.boardMeeting as any).create({
          data: clean({
            id: m.id,
            ...scheduleData,
            meetingType: m.meetingType || 'Board Meeting',
            chair: m.chair || 'TBD',
            status: m.status,
            minutes: m.minutes,
            notes: notesParts.length ? notesParts.join('\n') : null,
            heldAt: toDate(m.heldAt),
            confirmedBy: m.confirmedBy,
            directorsPresent: m.directorsPresent,
            minutesUrl: m.minutesUrl,
            createdBy: m.createdBy || 'usr-legal-001',
          }),
        });
        bmCreated++;
      }
    }
    console.log(`✓ Board meetings: ${bmCreated} created, ${bmUpdated} updated (user edits preserved)`);

    // ──────────────────────────────────────────────────────────────────────
    // REGULATORY CALENDAR
    // ──────────────────────────────────────────────────────────────────────
    console.log('Seeding regulatory calendar (2026)...');

    // Fetch seeded entities for name matching
    const seededEntities = await prisma.entity.findMany({ select: { id: true, name: true } });

    let calCreated = 0;
    let calSkipped = 0;

    for (const entry of calData.entries) {
      const entityId = matchEntityId(entry.entity_name, seededEntities);
      if (!entityId) { calSkipped++; continue; }

      const dueDate = new Date(entry.due_date);
      if (isNaN(dueDate.getTime())) { calSkipped++; continue; }

      const driNote = [
        entry.compliance_dri ? `Compliance DRI: ${entry.compliance_dri}` : '',
        entry.finance_dri    ? `Finance DRI: ${entry.finance_dri}`       : '',
      ].filter(Boolean).join(' | ');

      // Upsert so re-seeding is idempotent
      await (prisma as any).complianceObligation.upsert({
        where: {
          // Prisma doesn't have a unique constraint here, so use findFirst + create
          id: `cal-2026-${entityId}-${entry.report_name}`.slice(0, 25).replace(/[^a-z0-9-]/gi, '-'),
        },
        update: {},
        create: {
          id: `cal-2026-${entityId}-${entry.report_name}`.slice(0, 25).replace(/[^a-z0-9-]/gi, '-'),
          entityId,
          requirementType: entry.report_name,
          regulator: entry.regulator,
          description: [entry.frequency, entry.deadline_raw].filter(Boolean).join(' · '),
          dueDate,
          status: 'pending',
          owner: entry.lead_team || 'Compliance',
          notes: driNote || null,
          recurrence: entry.recurrence || 'annual',
          source: 'calendar',
          calendarYear: calData.year,
        } as any,
      });
      calCreated++;
    }
    console.log(`✓ Seeded ${calCreated} regulatory calendar entries (${calSkipped} skipped — no entity match)`);

    console.log('\nSeed complete ✓');
    console.log('Capital, Alerts, BankAccounts intentionally empty (no source data).');
  } catch (err) {
    console.error('Error seeding database:', err);
    throw err;
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
